import { EmployeeSidebar } from "@/components/EmployeeSidebar"
import '@/styles/globals.css'

export const metadata = {
  title: "Employee | Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children
}) {
  return (
    <div className="flex h-screen">
      <EmployeeSidebar />

      <div className="flex-1 flex flex-col">
        <main className="flex-1 overflow-y-auto p-6 bg-zinc-50">
          {children}
        </main>
      </div>
    </div>
  )
}
