import { EmployeeSidebar } from "@/_components/EmployeeSidebar"
import { Toaster } from "sonner"
import '@/_styles/globals.css'

export const metadata = {
  title: "Employee | Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children
}) {
  return (
    <div className="flex h-screen">
      <EmployeeSidebar />

      <div className="flex-1 flex flex-col"> 
        <Toaster position="top-right" richColors expand duration={3000} closeButton toastOptions={{
            className: "rounded-lg shadow-lg border border-slate-200",
            style: { fontSize: "14px", padding: "12px 16px" },
          }}
        />
        <main className="flex-1 overflow-y-auto p-6 bg-slate-100">
          {children}
        </main>
      </div>
    </div>
  )
}
