import type { Metadata } from "next"
import { Sidebar } from "@/components/Sidebar"
import '@/styles/globals.css'

export const metadata: Metadata = {
  title: "Admin | Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex h-screen">
      <Sidebar />

      <div className="flex-1 flex flex-col">
        <main className="flex-1 overflow-y-auto p-6 bg-zinc-50">
          {children}
        </main>
      </div>
    </div>
  )
}
