import SidebarServer from "@/_components/SidebarServer"
import '@/_styles/globals.css'
import { ReactQueryProvider } from '@/_context/useQueryClient';

export const metadata = {
  title: "Admin | Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <div className="flex h-screen">
      {/* ⬅️ ganti Sidebar jadi SidebarServer */}
      <SidebarServer />

      <div className="flex-1 flex flex-col">
        <main className="flex-1 overflow-y-auto p-4 bg-slate-100">
          <ReactQueryProvider>
            {children}
          </ReactQueryProvider>
        </main>
      </div>
    </div>
  )
}
